### Numpy Packages:
1. Numerical data
2. computations 

In [21]:
import numpy as np

### Difference between Numpy array and Python list
1. less memory
2. fast
3. convenient

In [22]:
# 1-dimentional array
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [23]:
print(a.ndim)

1


In [24]:
# multi-dimentional array
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
a1.ndim

2

In [26]:
a1.shape

(3, 3)

In [27]:
a.shape

(5,)

In [28]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a2.shape[0]) #rows
print(a2.shape[1]) #columns

4
3


In [29]:
a3=np.array([],dtype="int32")

In [31]:
a3=np.append(a3,int(input()))
a3

10


array([10])

In [32]:
a3=np.append(a3,[23,34,45,56,67])
a3

array([10, 23, 34, 45, 56, 67])

In [33]:
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### slicing:extract elements

In [34]:
print(a3[3])

45


In [35]:
print(a2[1,1])

5


In [36]:
print(a2[2:,:])

[[ 7  8  9]
 [10 11 12]]


In [37]:
print(a2[2:,0:2])

[[ 7  8]
 [10 11]]


In [38]:
print(a2[0,0:2])

[1 2]


In [39]:
print(a2[0::2,:])

[[1 2 3]
 [7 8 9]]


### iterate thriugh array:

In [40]:
for row in a2:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [41]:
list1=[[1,2,[3,4]]]
for i in list1:
    print(i)

[1, 2, [3, 4]]


In [42]:
for ele in a2.flat:
    print(ele,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [43]:
np.array(a2.flat)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### indexing with boolean array

In [44]:
arr1=np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [45]:
result=(arr1%2==0)
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [46]:
arr1[result]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## Appending Array

In [47]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
print(arr2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [49]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
print(np.vstack((arr1,arr2))) #vertical stack

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [50]:
print(np.hstack((arr1,arr2))) #horizontal stack

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


### Attributes:
1. size
2. itemsize
3. dtype
4. ndim
5. shape

In [51]:
arr=np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [52]:
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)


10
4
int32
2
(2, 5)


### Functions:
1. zeros
2. ones
3. full()
4. eye()
5. linspace()
6. arrange()
7. reshape()
8. ravel()

In [53]:
z=np.zeros((2,3),dtype="int32")
z

array([[0, 0, 0],
       [0, 0, 0]])

In [54]:
o=np.ones((3,3),dtype="int32")
o

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [55]:
f=np.full((2,2),"vijaya")
print(f)

[['vijaya' 'vijaya']
 ['vijaya' 'vijaya']]


In [56]:
#eye()
e=np.eye(3,dtype="int32")
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [57]:
#linspace()-->linear spacing elements
l=np.linspace(1,10,5)
l

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [58]:
a=np.arange(1,13,2) #range(start,stop,step)
a

array([ 1,  3,  5,  7,  9, 11])

In [59]:
a=a.reshape(2,3)
a

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [60]:
#ravel() -->flattens your array element
print(np.array(a.flat))
print(a.ravel())

[ 1  3  5  7  9 11]
[ 1  3  5  7  9 11]


### Function:
1. min()
2. max()
3. sum()
4. sqrt()
5. mean()
6. median()
7. std()

In [61]:
print(a.min())
print(a.max())

1
11


In [62]:
print(a.sum())

36


In [63]:
print(a.sum())
print(a.sum(axis=1))
print(a.sum(axis=0))

36
[ 9 27]
[ 8 12 16]


In [64]:
np.sqrt(a)

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479]])

In [65]:
np.mean(a)

6.0

In [66]:
np.median(a)

6.0

In [67]:
np.std(a)

3.415650255319866

### dot() -->Matrix multiplication
arr1=mxn
arr2=nx1

In [72]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
arr1.dot(arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [69]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
#transpose of an array
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Applying user-defined function:

In [73]:
list1=list(range(1,20))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [75]:
a=np.array(list1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [76]:
result=[x/(x+1) for x in list1]
result

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091,
 0.9166666666666666,
 0.9230769230769231,
 0.9285714285714286,
 0.9333333333333333,
 0.9375,
 0.9411764705882353,
 0.9444444444444444,
 0.9473684210526315,
 0.95]

In [77]:
f=np.vectorize(lambda x:x/(x+1))
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])