In [1]:
from numpy import random
print(random.randint(1,100))#random integer in given range
print(random.rand())#float number 0-1

66
0.06097925888988387


In [2]:
#create n-dimensional array with random integer  values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[74 72 63]
[[78 81 73  3]
 [24 51 10  7]
 [76 27 95 88]]
[[[ 6 32]
  [80 36]
  [52 31]
  [89 83]]

 [[81 39]
  [74 85]
  [18 89]
  [70  3]]

 [[ 0 82]
  [91  6]
  [86 16]
  [58 68]]]


In [4]:
#create n-dimensional array with random floating values
print(random.rand(3))
print(random.rand(3,4))
print(random.rand(3,4,2))

[0.97918783 0.01013264 0.84114975]
[[0.02187568 0.97870657 0.3523968  0.21801171]
 [0.76562605 0.83474058 0.46297281 0.79665951]
 [0.10627939 0.18947135 0.64608348 0.18096509]]
[[[0.04665054 0.20816176]
  [0.89339344 0.63712   ]
  [0.4597902  0.01811344]
  [0.44203302 0.96580356]]

 [[0.70610498 0.91948269]
  [0.64016927 0.38358918]
  [0.13636421 0.6942228 ]
  [0.30753034 0.04909261]]

 [[0.52048526 0.56145506]
  [0.36661442 0.75051962]
  [0.96595821 0.36761822]
  [0.95784584 0.91522395]]]


In [5]:
a = random.randint(100,size=(3,2)).ravel()
a

array([71, 55,  8, 30, 11, 46])

In [6]:
#single element will be selected
random.choice(a)

11

In [7]:
#for generating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size=(3,4))

array([[3, 2, 3, 1],
       [3, 4, 3, 4],
       [4, 2, 3, 1]])

Pandas:
Data manipulation,analysis and cleaning
Tabulated,Unlabelled

Creating a DataFrame
using 2 dictionaries

In [9]:
import pandas as pd
import numpy as np
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}
dict2 = {'a':5,'b':6,'c':7,'d':8,'e':9}
data = {"First":dict1,"Second":dict2}
df = pd.DataFrame(data,dtype=np.int32)
df


First  Second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [10]:
#simple dictionary --> DataFrame
d1 = {"name":["vijaya","rahul","hemani"],"address":["hyd","ndyl","TG"]}
df1 = pd.DataFrame(d1)
df1

name address
0  vijaya     hyd
1   rahul    ndyl
2  hemani      TG

In [11]:
#using series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([12.23,23.32,45.3,52.45,25.33,65.3,85.23,6.32,54.55,55.24])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"column1":s1,"column2":s2,"column3":s3}
df3 = pd.DataFrame(data)
df3

column1  column2 column3
0        1    12.23       a
1        2    23.32       b
2        3    45.30       c
3        4    52.45       d
4        5    25.33       e
5        6    65.30       f
6        7    85.23       g
7        8     6.32       h
8        9    54.55       i
9       10    55.24       j

Selecting data from dataframe:¶
loc
iloc

In [12]:
df3[["column2","column3"]]

column2 column3
0    12.23       a
1    23.32       b
2    45.30       c
3    52.45       d
4    25.33       e
5    65.30       f
6    85.23       g
7     6.32       h
8    54.55       i
9    55.24       j

In [13]:
df3["column2"]

0    12.23
1    23.32
2    45.30
3    52.45
4    25.33
5    65.30
6    85.23
7     6.32
8    54.55
9    55.24
Name: column2, dtype: float64

In [14]:
#using single column
df3.loc[:,"column1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [15]:
df3.loc[0:5,["column1","column2","column3"]]

column1  column2 column3
0        1    12.23       a
1        2    23.32       b
2        3    45.30       c
3        4    52.45       d
4        5    25.33       e
5        6    65.30       f

In [16]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [17]:
df3.iloc[0:4,0:1]

column1
0        1
1        2
2        3
3        4

Retrieving information of dataframe

In [18]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   column1  10 non-null     int64  
 1   column2  10 non-null     float64
 2   column3  10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [19]:
df3.shape

(10, 3)

In [20]:
df3.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [21]:
df3.index

RangeIndex(start=0, stop=10, step=1)

Viewing data from dataframe:¶
head()
tail()
sample()

In [22]:
df3.head(3)

column1  column2 column3
0        1    12.23       a
1        2    23.32       b
2        3    45.30       c

In [23]:
df3.tail()

column1  column2 column3
5        6    65.30       f
6        7    85.23       g
7        8     6.32       h
8        9    54.55       i
9       10    55.24       j

In [24]:
df3.sample(2)

column1  column2 column3
2        3    45.30       c
1        2    23.32       b

In [25]:
df3.describe()

column1    column2
count  10.00000  10.000000
mean    5.50000  42.527000
std     3.02765  25.051025
min     1.00000   6.320000
25%     3.25000  23.822500
50%     5.50000  48.875000
75%     7.75000  55.067500
max    10.00000  85.230000

Renaming columns:

In [26]:
#renaming column headers
df3 = df3.rename(columns={"column1":"First",
                          "column2":"Second",
                          "column3":"Third"})
df3

First  Second Third
0      1   12.23     a
1      2   23.32     b
2      3   45.30     c
3      4   52.45     d
4      5   25.33     e
5      6   65.30     f
6      7   85.23     g
7      8    6.32     h
8      9   54.55     i
9     10   55.24     j