In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

In [24]:

data=pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/homeprices.csv ")
data

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

**Dummy VariableUsing Scikit-Learn  Library**

In [25]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [26]:
price_data=data.copy()
price_data

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [27]:
price_data.town=le.fit_transform(data.town)
price_data

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

**OneHotEncoder-->similar to pd.get_dummies**

In [29]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [30]:
column_transformer=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')

In [34]:
data=column_transformer.fit_transform(data)
data

array([[0.00e+00, 1.00e+00, 0.00e+00, 0.00e+00, 2.60e+03, 5.50e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 0.00e+00, 3.00e+03, 5.65e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 0.00e+00, 3.20e+03, 6.10e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 0.00e+00, 3.60e+03, 6.80e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 0.00e+00, 4.00e+03, 7.25e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 1.00e+00, 2.60e+03, 5.85e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 1.00e+00, 2.80e+03, 6.15e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 1.00e+00, 3.30e+03, 6.50e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 1.00e+00, 3.60e+03, 7.10e+05],
       [1.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 2.60e+03, 5.75e+05],
       [1.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 2.90e+03, 6.00e+05],
       [1.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 3.10e+03, 6.20e+05],
       [1.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 3.60e+03, 6.95e+05]])

In [35]:
X=pd.DataFrame(data)
X

0    1    2    3       4         5
0   0.0  1.0  0.0  0.0  2600.0  550000.0
1   0.0  1.0  0.0  0.0  3000.0  565000.0
2   0.0  1.0  0.0  0.0  3200.0  610000.0
3   0.0  1.0  0.0  0.0  3600.0  680000.0
4   0.0  1.0  0.0  0.0  4000.0  725000.0
5   1.0  0.0  0.0  1.0  2600.0  585000.0
6   1.0  0.0  0.0  1.0  2800.0  615000.0
7   1.0  0.0  0.0  1.0  3300.0  650000.0
8   1.0  0.0  0.0  1.0  3600.0  710000.0
9   1.0  0.0  1.0  0.0  2600.0  575000.0
10  1.0  0.0  1.0  0.0  2900.0  600000.0
11  1.0  0.0  1.0  0.0  3100.0  620000.0
12  1.0  0.0  1.0  0.0  3600.0  695000.0

**Splitting the Dataset**

In [36]:
price=pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/homeprices.csv ")


In [38]:
X=price.iloc[:,0:2]
X

town  area
0   monroe township  2600
1   monroe township  3000
2   monroe township  3200
3   monroe township  3600
4   monroe township  4000
5      west windsor  2600
6      west windsor  2800
7      west windsor  3300
8      west windsor  3600
9       robinsville  2600
10      robinsville  2900
11      robinsville  3100
12      robinsville  3600

In [39]:
y=price.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [40]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [41]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(10, 2)
(3, 2)
(10,)
(3,)


In [42]:
X_train

town  area
4   monroe township  4000
8      west windsor  3600
0   monroe township  2600
9       robinsville  2600
2   monroe township  3200
12      robinsville  3600
11      robinsville  3100
7      west windsor  3300
3   monroe township  3600
6      west windsor  2800

**Feature scalling**

In [45]:
sample=pd.DataFrame({'W.E':[2,4,5,6,7,8],'Age':[28,25,32,45,33,42],
                     'Salary':[300000,400000,500000,600000,800000,700000],
                     'Distance':[10,12,23,32,15,17],
                     'Expected salary':[400000,500000,600000,700000,900000,800000]})
sample

W.E  Age  Salary  Distance  Expected salary
0    2   28  300000        10           400000
1    4   25  400000        12           500000
2    5   32  500000        23           600000
3    6   45  600000        32           700000
4    7   33  800000        15           900000
5    8   42  700000        17           800000

In [46]:
from sklearn.preprocessing import scale
scaled_data=scale(sample)
scaled_data

array([[-1.69030851, -0.86233265, -1.46385011, -1.09980534, -1.46385011],
       [-0.6761234 , -1.28184583, -0.87831007, -0.83046526, -0.87831007],
       [-0.16903085, -0.30298174, -0.29277002,  0.6509052 , -0.29277002],
       [ 0.3380617 ,  1.51490871,  0.29277002,  1.86293558,  0.29277002],
       [ 0.84515425, -0.16314401,  1.46385011, -0.42645513,  1.46385011],
       [ 1.35224681,  1.09539553,  0.87831007, -0.15711505,  0.87831007]])

**Using standaedacaler**

In [ ]:
price_data=data.copy()
price_data

In [50]:
scaled_data=pd.DataFrame(scaled_data)
scaled_data

0         1        2         3        4
0 -1.690309 -0.862333 -1.46385 -1.099805 -1.46385
1 -0.676123 -1.281846 -0.87831 -0.830465 -0.87831
2 -0.169031 -0.302982 -0.29277  0.650905 -0.29277
3  0.338062  1.514909  0.29277  1.862936  0.29277
4  0.845154 -0.163144  1.46385 -0.426455  1.46385
5  1.352247  1.095396  0.87831 -0.157115  0.87831

In [51]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sample=sc.fit_transform(sample)
sample

array([[-1.69030851, -0.86233265, -1.46385011, -1.09980534, -1.46385011],
       [-0.6761234 , -1.28184583, -0.87831007, -0.83046526, -0.87831007],
       [-0.16903085, -0.30298174, -0.29277002,  0.6509052 , -0.29277002],
       [ 0.3380617 ,  1.51490871,  0.29277002,  1.86293558,  0.29277002],
       [ 0.84515425, -0.16314401,  1.46385011, -0.42645513,  1.46385011],
       [ 1.35224681,  1.09539553,  0.87831007, -0.15711505,  0.87831007]])

In [52]:
sample=pd.DataFrame(sample)
sample

0         1        2         3        4
0 -1.690309 -0.862333 -1.46385 -1.099805 -1.46385
1 -0.676123 -1.281846 -0.87831 -0.830465 -0.87831
2 -0.169031 -0.302982 -0.29277  0.650905 -0.29277
3  0.338062  1.514909  0.29277  1.862936  0.29277
4  0.845154 -0.163144  1.46385 -0.426455  1.46385
5  1.352247  1.095396  0.87831 -0.157115  0.87831

In [55]:
standard_data=sample.copy()
standard_data

0         1        2         3        4
0 -1.690309 -0.862333 -1.46385 -1.099805 -1.46385
1 -0.676123 -1.281846 -0.87831 -0.830465 -0.87831
2 -0.169031 -0.302982 -0.29277  0.650905 -0.29277
3  0.338062  1.514909  0.29277  1.862936  0.29277
4  0.845154 -0.163144  1.46385 -0.426455  1.46385
5  1.352247  1.095396  0.87831 -0.157115  0.87831

**MinMaxScaler:**

In [59]:
from sklearn.preprocessing import MinMaxScaler
ms= MinMaxScaler
ms.fit(standard_data)
standard_data=ms.transform(standard_data)
standard_data

TypeError: ignored

In [57]:
standard_data=pd.DataFrame(standard_data)
standard_data

0         1        2         3        4
0 -1.690309 -0.862333 -1.46385 -1.099805 -1.46385
1 -0.676123 -1.281846 -0.87831 -0.830465 -0.87831
2 -0.169031 -0.302982 -0.29277  0.650905 -0.29277
3  0.338062  1.514909  0.29277  1.862936  0.29277
4  0.845154 -0.163144  1.46385 -0.426455  1.46385
5  1.352247  1.095396  0.87831 -0.157115  0.87831